### ISSUE TITLE
Google Chrome crash on start record

### ISSUE THREAD

**Issue by CoolONEOfficial** [Bujupah/web_media_recorder#1]
I forked repo, run `flutter create .` in /example folder, move main.dart in lib, add dependency in pub spec file and run the example. After pressing on start button google chrome is crashing..

**Comment by deepikadt** [comment]
Same issue I am facing. I am running it on macOS chrome browser.

**Comment by syedtalha** [comment]
any response on this?

**Comment by Bujupah** [comment]
Sorry for the undefined delay, will check this ASAP

**Comment by syedtalha** [comment]
this happens on Google Chrome Android version

**Comment by Bujupah** [comment]
This project is no longer maintained, please check the new project on [github](https://github.com/Bujupah/browser_api) or [pub.dev](https://pub.dev/packages/browser_api)

**Comment by Bujupah** [comment]
@syedtalha  @deepikadt  @CoolONEOfficial 
This project is no longer maintained, please check the new project on [github](https://github.com/Bujupah/browser_api) or [pub.dev](https://pub.dev/packages/browser_api)
