### ISSUE TITLE
audio sample rate

### ISSUE THREAD

**Issue by xnio94** [Bujupah/web_media_recorder#2]
audio data without knowing the exact sample rate is unusable, and the package does not provide the sample rate of the data.
how i can get the sample rate of the data

i searched how to add this feature and i found that you can actually pass a parameter object to `getUserMedia`
so instead of `html.window.navigator.getUserMedia(audio: true)` we can use `html.window.navigator.getUserMedia(audio : {'sampleRate':16000})`

but I'm not sure how to do this correctly.

**Comment by Bujupah** [comment]
@xnio94 
This project is no longer maintained, please check the new project on [github](https://github.com/Bujupah/browser_api) or [pub.dev](https://pub.dev/packages/browser_api)
