### ISSUE TITLE
web_media_recorder return wrong data

### ISSUE THREAD

**Issue by xnio94** [Bujupah/web_media_recorder#3]
i tried the example but the app printed incorrect data
how i know: 
i copied the data to a python variable and then play the audio using IPython.display.Audio using different sample rate (see [this](https://github.com/Bujupah/web_media_recorder/issues/2)) but i only get noise.
is there a way to play the returned data inside of flutter, in other words, how did you tested the package to know if its really returning the correct data.

**Comment by eugenioamato** [comment]
soundpool plugin has a uint8list method that works ok

static Soundpool pool = Soundpool(streamType: StreamType.notification);
  static void PlaySound(Uint8List data)
  {
    pool.loadAndPlayUint8List(data);
  }

**Comment by Bujupah** [comment]
@xnio94 
@eugenioamato 

This project is no longer maintained, please check the new project on [github](https://github.com/Bujupah/browser_api) or [pub.dev](https://pub.dev/packages/browser_api)
