### ISSUE TITLE
no streams received under ios chrome

### ISSUE THREAD

**Issue by eugenioamato** [Bujupah/web_media_recorder#4]
The plugin works perfectly on android and desktop (chrome on macOs), but doesn't work under Ios browsers!
chrome://inspect under iphone 11 traces logs until this line
html.window.navigator
          .getUserMedia(audio: true)
          .then((stream) {
---->.                            ????

Under Ios indeed no stream is provided by chrome browser, and also Safari stops at the same point but i have no way to debug it.
Maybe it has to do with some permission-level issue?
I am actually not making any request for permission, maybe we need some meta-tag? 

under Chrome on macOs Catalina it asks it automatically when recording start (with a popup i did not make), and it works,
under Safari on macOs it doesn't work and no errors are provided.

under Android it doesn't ask nothing (but still works under all browsers).

**Comment by Bujupah** [comment]
@eugenioamato 
This project is no longer maintained, please check the new project on [github](https://github.com/Bujupah/browser_api) or [pub.dev](https://pub.dev/packages/browser_api)
